### SPRING CONFIGURATION ###
server:
  # the port of the server
  port: 8081

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

### INFLUX (v2) CONFIGURATION ###
# Client
influx:
  url: http://localhost:8086
  username: ""
  password: ""
  token: ""
  org: ""
  bucket: ""
  logLevel: BASIC # The log level for logging the HTTP request and HTTP response
  readTimeout: 10s # Read timeout for OkHttpClient
  writeTimeout: 10s # Write timeout for OkHttpClient
  connectTimeout: 10s # Connection timeout for OkHttpClient

# Micrometer registry
management:
  influx:
    metrics:
      export:
        enabled: false

### DWH CONFIGURATION ###
dwh:
  # secret to access the /dwh endpoint
  token: my_secret

  # the metrics and related queries to use and export
  metrics:
    - name: my-metric|${service}|${http_path}
      database: inspectit
      query: |
        SELECT SUM("sum") / SUM("count")
        FROM "inspectit"."autogen"."http_in_responsetime"
        GROUP BY time(${interval}), "service", "http_path" FILL(null)
